services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/workdir/frontend
      - /workdir/frontend/node_modules
    env_file:
      - ./frontend/.env
    working_dir: /workdir/frontend
    ports:
      - "5173:5173"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /workdir/backend
    volumes:
      - ./backend:/workdir/backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"