FROM python:latest

# install stage
COPY requirements.txt requirements.txt
COPY requirements.dev.txt requirements.dev.txt
RUN pip install -r requirements.txt -r requirements.dev.txt


EXPOSE 5000

CMD ["flask", "--app", "app.py", "--debug", "run", "--host=0.0.0.0"]